---
name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check out the code
      uses: actions/checkout@v3
    - name: Test
      run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
    - name: Lint
      run: docker compose run --rm app sh -c "flake8"  